config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newsletter.urls", namespace="newsletter")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path

from newsletter.apps import NewsletterConfig
from newsletter.models import Mailing
from newsletter.views import (
    MessageListView,
    MailingCreateView,
    MailingDetailView,
    MailingDeleteView,
    MailingUpdateView,
    MailingListView,
    ClientCreateView,
    ClientListView,
    ClientDetailView,
    ClientUpdateView,
    ClientDeleteView,
)

app_name = NewsletterConfig.name


urlpatterns = [
    path("", MailingListView.as_view(), name="mailing_list"),
    path("create/", MailingCreateView.as_view(), name="mailing_create"),
    path("update/<int:pk>", MailingUpdateView.as_view(), name="mailing_update"),
    path("delete/<int:pk>", MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailing/<int:pk>", MailingDetailView.as_view(), name="mailing_info"),
    path("client_create/", ClientCreateView.as_view(), name="client_create"),
    path("client_list/", ClientListView.as_view(), name="client_list"),
    path("client_detail/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("client_update/<int:pk>/", ClientUpdateView.as_view(), name="client_update"),
    path("client_delete/<int:pk>/", ClientDeleteView.as_view(), name="client_delete"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import (
    UserCreateView,
    email_verification,
    RecoveryPasswordView,
    UserProfileView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("activate/<str:token>/", email_verification, name="activate"),
    path("recovery/", RecoveryPasswordView.as_view(), name="recovery"),
    path(
        "profile/<int:pk>/", UserProfileView.as_view(), name="profile"
    ),  # Для показа профиля
]

newsletter/models.py
from django.db import models

from users.models import User

NULLABLE = {"null": True, "blank": True}


class Client(models.Model):
    """Клиент сервиса"""

    name = models.CharField(
        max_length=255, verbose_name="ФИО", help_text="Введите имя клиента"
    )
    email = models.EmailField(
        max_length=100, verbose_name="Почта для рассылки", help_text="Заполните почту"
    )
    comment = models.TextField(max_length=250, verbose_name="Комментарий")
    autor = models.ForeignKey(
        User, verbose_name="автор", on_delete=models.SET_NULL, **NULLABLE
    )

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Message(models.Model):
    """Сообщение для рассылки"""

    theme = models.CharField(max_length=100, verbose_name="Тема письма")
    content = models.TextField(max_length=500, verbose_name="Содержание письма")
    autor = models.ForeignKey(
        User, verbose_name="автор", on_delete=models.SET_NULL, **NULLABLE
    )

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ["theme"]

    def __str__(self):
        return self.theme


class Mailing(models.Model):
    """Рассылка"""

    date_of_first_mail = models.DateTimeField(verbose_name="Дата первой отправки")
    periodicity = models.CharField(
        max_length=1,
        verbose_name="Периодичность",
        choices={"D": "Раз в день", "W": "Раз в неделю", "M": "Раз в месяц"},
    )
    status = models.CharField(
        max_length=20,
        verbose_name="Статус рассылки",
        choices={"C": "Создана", "W": "Запущена", "F": "Завершена"},
    )
    message_id = models.OneToOneField(
        Message,
        on_delete=models.CASCADE,
        verbose_name="Сообщение",
        help_text="Выберите сообщение",
    )
    client_id = models.ManyToManyField(Client, verbose_name="Клиенты")
    autor = models.ForeignKey(
        User, verbose_name="автор", on_delete=models.SET_NULL, **NULLABLE
    )

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ["message_id"]
        permissions = [
            ("can_view_mailing", "Can view mailing"),
            ("can_disable_mailing", "Can disable mailing"),
        ]

    def __str__(self):
        return str(self.date_of_first_mail)


class Attempt(models.Model):
    """Попытка отправки письма"""

    date_first_attempt = models.DateTimeField(
        verbose_name="Дата первой попытки", auto_now_add=True
    )
    date_last_attempt = models.DateTimeField(
        verbose_name="Дата последней попытки", auto_now=True
    )
    status = models.BooleanField(verbose_name="Статус попытки")
    server_response = models.CharField(max_length=100, verbose_name="Ответ сервера")
    mailing_id = models.ForeignKey(
        Mailing, on_delete=models.CASCADE, verbose_name="Рассылка", **NULLABLE
    )

    class Meta:
        verbose_name = "Попытка отправки"
        verbose_name_plural = "Попытки отправки"
        ordering = ["-date_first_attempt"]

    def __str__(self):
        return self.date_first_attempt

newsletter/forms.py
from django.forms import ModelForm, BooleanField

from newsletter.models import Message, Mailing


class StyleFormMixin(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        fields = "__all__"


class MailingForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        exclude = ("autor",)

newsletter/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from newsletter.forms import MessageForm, MailingForm
from newsletter.models import Mailing, Message, Client


class MessageListView(ListView):
    model = Message


class MessageDetailView(DetailView):
    model = Message


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("newsletter:mailing_list")


class MessageUpdateView(UpdateView):
    model = Message


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy("newsletter:mailing_list")


class MailingListView(ListView):
    model = Mailing


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    form_class = MailingForm


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("newsletter:mailing_list")
    permission_required = "newsletter.add_mailing"

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.autor = user
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("newsletter:mailing_list")


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy("newsletter:mailing_list")
    permission_required = "newsletter.delete_mailing"


class ClientCreateView(LoginRequiredMixin, CreateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Client


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Client


class ClientDeleteView(DeleteView):
    model = Client


class ClientListView(LoginRequiredMixin, ListView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Client


class ClientDetailView(LoginRequiredMixin, DetailView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Client

newsletter/templates/newsletter/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mailing</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Рассылки</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Рассылки</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-primary" href="{% url 'users:profile' request.user.pk %}">Профиль</a>
            <!--        <a class="p-2 btn btn-danger" href="{% url 'users:logout' %}" >Выход</a>-->
            <!--        Можно было бы использовать в Django выше 4.2-->
            {% if user.is_staff or user.is_superuser %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'admin:index' %}">Админка</a>
            {% endif %}
            <form action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Выйти</button>
            </form>
        {% else %}
            <a class="p-2 btn btn-success" href="{% url 'users:login' %}">Вход</a>
        {% endif %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылки</h1>
    <p class="lead">Сервис рассылок</p>
    <a class="btn btn-primary" href="{% url 'newsletter:mailing_create' %}" role="button">Создать Рассылку</a>
</div>

{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/admin/">В админку</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

newsletter/templates/newsletter/mailing_confirm_delete.html
{% extends 'newsletter/index.html' %}
{% load tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.theme}} </h4>
                </div>
                <div class="card-body">
                    <form method="post">{% csrf_token %}
                    <p>Вы уверены, что хотите удалить сообщение "{{ object }}"?</p>
                    {{ form }}
                        <input class="btn btn-primary" type="submit" value="Да">
                        <a class="btn btn-primary" href="{% url 'newsletter:mailing_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/mailing_detail.html
{% extends 'newsletter/index.html' %}
{% load tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.message_id}} </h4>
                </div>
                <div class="card-body">
                    <p class="card-text">Статус: {{object.status}}</p>
                    <p class="card-text">Периодичность: {{object.periodicity}}</p>
                    <p class="card-text">Клиенты: {{object.client_id}}</p>
                    <p class="card-text">Автор: {{object.autor}}</p>
                    <a class="btn btn-primary" href="{% url 'newsletter:mailing_list' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/mailing_form.html
{% extends 'newsletter/index.html' %}
{% block content %}
    <div class="container">
        <form class="text-body-color mb-3 form-control" method="post" enctype="multipart/form-data">
            <div class="col-8">
                <div class="card">
                    {% if object %}
                        <p class="card-text">Редактирование</p>
                    {% else %}
                        <p class="card-text">Создание</p>
                    {% endif %}
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                    <a class="btn btn-primary" href="{% url 'newsletter:mailing_list' %}" role="button">Отмена</a>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

newsletter/templates/newsletter/mailing_list.html
{% extends 'newsletter/index.html' %}
{% load tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for mailing in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <p class="card-text">{{ mailing.message_id }}</p>
                        <p class="card-text">{{ mailing.client_id | slice:":100" }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'newsletter:mailing_info' mailing.pk %}"
                                   role="button">Посмотреть</a>
                                <a class="btn btn-primary" href="{% url 'newsletter:mailing_update' mailing.pk %}"
                                   role="button">Изменить</a>
                                <a class="btn btn-primary" href="{% url 'newsletter:mailing_delete' mailing.pk %}"
                                   role="button">Удалить</a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/message_confirm_delete.html
{% extends 'newsletter/index.html' %}
{% load tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.theme}} </h4>
                </div>
                <div class="card-body">
                    <form method="post">{% csrf_token %}
                    <p>Вы уверены, что хотите удалить сообщение "{{ object }}"?</p>
                    {{ form }}
                        <input class="btn btn-primary" type="submit" value="Да">
                        <a class="btn btn-primary" href="{% url 'newsletter:message_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/message_detail.html
{% extends 'newsletter/index.html' %}
{% load tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.theme}} </h4>
                </div>
                <div class="card-body">
                    <p class="card-text">Содержимое: {{object.content}}</p>
                    <a class="btn btn-primary" href="{% url 'newsletter:message_list' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/message_form.html
{% extends 'newsletter/index.html' %}
{% block content %}
<div class="container">
    <div class="row text">
        <div class="col-12">
            <div class="row">
                <div class="col-8">
                    <div class="card">
                        <div class="card-body">
                            <form class ="text-body-color mb-3 form-control" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">
                                    {% if object %}
                                        Сохранить
                                    {% else %}
                                        Создать
                                    {% endif %}
                                </button>
                                <a class="btn btn-primary" href="{% url 'newsletter:message_list' %}" role="button">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/message_list.html
{% extends 'newsletter/index.html' %}
{% load tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for message in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <p class="card-text">{{ message.theme }}</p>
                        <p class="card-text">{{ message.content | slice:":100" }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'newsletter:message_info' message.pk %}"
                                   role="button">Посмотреть</a>
                                <a class="btn btn-primary" href="{% url 'newsletter:message_update' message.pk %}"
                                   role="button">Изменить</a>
                                <a class="btn btn-primary" href="{% url 'newsletter:message_delete' message.pk %}"
                                   role="button">Удалить</a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}